server:
  port: 6202
spring:
  application:
    name: blog-follow
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 20120412
    url: jdbc:mysql://localhost:3306/blog
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6201/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
