server:
  port: 6002
spring:
  application:
    name: yjx-query
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 20120412
    url: jdbc:mysql://39.104.201.171:3306/yjx
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.example.query.mapper
  configuration:
    map-underscore-to-camel-case: true
eureka:
  client:
    service-url:
      defaultZone: http://39.104.201.171:6001/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
