package com.example.systemlogin.service;

import org.springframework.stereotype.Service;

@Service
public class password {
    public String pass(String password){
        char[] pass=password.toCharArray();
        StringBuilder pass2= new StringBuilder();
        for(char i:pass){
            if(i=='1'){
                pass2.append("你");
            }
            if(i=='2'){
                pass2.append("干");
            }
            if(i=='3'){
                pass2.append("嘛");
            }
            if(i=='4'){
                pass2.append("哎");
            }
            if(i=='5'){
                pass2.append("哟");
            }
            if(i=='6'){
                pass2.append("赶");
            }
            if(i=='7'){
                pass2.append("紧");
            }
            if(i=='8'){
                pass2.append("滚");
            }
            if(i=='9'){
                pass2.append("蛋");
            }
            if(i=='0'){
                pass2.append("大");
            }
            if(i=='a'){
                pass2.append("聪");
            }
            if(i=='b'){
                pass2.append("明");
            }
            if(i=='c'){
                pass2.append("啥");
            }
            if(i=='d'){
                pass2.append("也");
            }
            if(i=='e'){
                pass2.append("不");
            }
            if(i=='f'){
                pass2.append("是");
            }
            if(i=='g'){
                pass2.append("去");
            }
            if(i=='h'){
                pass2.append("世");
            }
            if(i=='i'){
                pass2.append("被");
            }
            if(i=='j'){
                pass2.append("骗");
            }
            if(i=='k'){
                pass2.append("了");
            }
            if(i=='l'){
                pass2.append("傻");;
            }
            if(i=='m'){
                pass2.append("人");
            }
            if(i=='n'){
                pass2.append("没");
            }
            if(i=='o'){
                pass2.append("福");
            }
            if(i=='p'){
                pass2.append("哈");
            }
            if(i=='q'){
                pass2.append("溜");
            }
            if(i=='r'){
                pass2.append("脚");
            }
            if(i=='s'){
                pass2.append("底");
            }
            if(i=='t'){
                pass2.append("抹");
            }
            if(i=='u'){
                pass2.append("油");
            }
            if(i=='v'){
                pass2.append("我");
            }
            if(i=='w'){
                pass2.append("孝");
            }
            if(i=='x'){
                pass2.append("死");
            }
            if(i=='y'){
                pass2.append("完");
            }
            if(i=='z'){
                pass2.append("结");
            }
        }
        return pass2.toString();
    }
}
